import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Container } from 'app/components/styled'
import Header from 'app/components/Header'

export default function Home() {
  const router = useRouter();
  console.log(router.query.id)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Container>
        <p>Post: {router.query.id}</p>
      </Container>
    </>
  )
}
