import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { getArticles } from '@/lib/notion/api'
import Center from '@/components/Center'
import styles from './style.module.css'
import { Dribbble, Figma, GitHub, Twitter } from 'react-feather'

export async function generateMetadata() {
  const { status, posts } = await getArticles()
  if (status!==200) {
    return { notFound: true }
  }

  return {
    posts
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Hal&apos;s castle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Hero/>
        <div className={styles['group-title']}></div>
      </Center>
    </>
  )
}

function Hero () {
  return (
    <div className="flex gap-6 mt-16 px-4 py-12">
      <Image src="/images/avatar.png" alt="Avatar" width={96} height={96} className="flex-shrink-0 rounded-full"/>
      <div>
        <h1>嗨，我是 Hal 🤔</h1>
        <p>你好，我是一名设计师。这是我的个人网站，随意逛逛，希望喜欢。你也可以在下面这些地方找到我。</p>
        <div className={styles['social-links']}>
          <SocialLink>
            <Figma size={20}/>
          </SocialLink>
          <SocialLink>
            <GitHub size={20}/>
          </SocialLink>
          <SocialLink>
            <Twitter size={20}/>
          </SocialLink>
          <SocialLink>
            <Dribbble size={20}/>
          </SocialLink>
        </div>
      </div>
    </div>
  )
}

function SocialLink ({ children }) {
  return (
    <div className={styles['social-link']}>
      { children }
    </div>
  )
}
