import React from 'react'
import Head from 'next/head'
import { Container } from 'app/components/styled'
import Header from 'app/components/Header'
import ArticleCard from 'app/components/ArticleCard'
import { getArticles } from '@/lib/notion/api'

export async function getStaticProps() {
  const { status, posts } = await getArticles()

  if (status!==200) {
    return { notFound: true }
  }

  return {
    props: {
      posts
    }
  };
}

export default function Home({ posts }) {
  console.log(posts)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Container>
        <main>
          <h2>
            <span>所有文章</span>
          </h2>
          {
            posts.map(post =>
              <ArticleCard
                key={post.id}
                id={post.id}
                date={post.created_time}
                src={post.cover && post.cover.file.url}
                title={post.title}
                tags={post.tags}
              />
            )
          }
        </main>
      </Container>
    </>
  )
}
