import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import Link from 'next/link'
import { ArrowRight } from 'react-feather'
import Header from '@/components/Header'
import { Container, Tag } from '@/components/styled'
import ArticleCard from '@/components/ArticleCard'

const Hero = styled.div`
  max-width: 720px;
  margin: 0 auto;
  margin-top: 64px;
  padding: 48px 16px;
  img {
    width: 96px;
    height: 96px;
    margin-bottom: 8px;
    border-radius: 48px;
  }
  h1 {
    margin: 0;
    margin-bottom: 8px;
    font-size: 40px;
    font-weight: 700;
  }
  p {
    margin: 0;
    font-size: 20px;
    color: ${({theme}) => theme.colors.textTertiary};
  }
`

const Articles = styled.div`
  max-width: 960px;
  margin: 0 auto;
  padding: 48px 16px;
`

const GroupTitle = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  color: #787878;
  font-size: 28px;
  font-weight: 600;
  >a {
    display: flex;
    align-items: center;
    color: #787878;
  }
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Container>
        <Hero>
          <img src="/images/avatar.png" alt="Avatar"/>
          <h1>嗨，我是 Hal 🤔</h1>
          <p>你好，我是一名设计师。这是我的个人网站，随意逛逛，希望喜欢。你也可以在下面这些地方找到我。</p>
        </Hero>
        <Articles>
          <GroupTitle>
            <span>最近发布</span>
            <Tag as={Link} href="/blog">全部<ArrowRight size={16}/></Tag>
          </GroupTitle>
          <ArticleCard
            src="/images/wugongshan.png"
            date="2022年7月21日"
            title="武功山徒步"
            tags={['徒步', '山']}
          />
          <ArticleCard
            src='/images/chaoshan.png'
            date="2017年3月2日"
            title="我来到深圳啦"
            tags={['城市', '工作']}
          />
          <ArticleCard
            src="/images/beijing.png"
            date="2016年7月2日"
            title="离开北京"
            tags={['城市', '工作']}
          />
        </Articles>
      </Container>
    </>
  )
}
